#!/bin/bash

if [ ! -d "venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv venv
    echo "Virtual environment created."
fi

source venv/bin/activate

if ! pip freeze | grep -q "mark-my-kindle-citations"; then
    pip install -e . --quiet
fi

mark-my-kindle-citations "$@"
